album_data = [
    {
        'artist': 1,
        'title': 'Lover',
        'cover': 'https://upload.wikimedia.org/wikipedia/en/c/cd/Taylor_Swift_-_Lover.png',
        'description': 'songwriter Taylor Swift. It was released on August 23, 2019, through Republic Records, and is her first album release after her departure from Big Machine Records, which resulted in a highly publicized dispute.',
        'likes': 2303533,
        'release_date': '2019-07-23',
        'genre': [1, 2],
    },
    {
        'artist': 1,
        'title': 'Reputation',
        'cover': 'https://upload.wikimedia.org/wikipedia/en/f/f2/Taylor_Swift_-_Reputation.png',
        'description': 'Reputation (stylized in all lowercase) is the sixth studio album by American singer-songwriter Taylor Swift. It was released on November 10, 2017, by Big Machine Records, and would be her last release under the label.',
        'likes': 428474,
        'release_date': '2017-11-10',
        'genre': [1, 2, 3, 8],
    },
    {
        'artist': 2,
        'title': 'Purpose',
        'cover': 'https://upload.wikimedia.org/wikipedia/en/2/27/Justin_Bieber_-_Purpose_%28Official_Album_Cover%29.png',
        'description': 'Recordings and School Boy Records on November 13, 2015, as the follow-up to his 2012 album “Believe”. ',
        'likes': 43846423,
        'release_date': '2015-11-13',
        'genre': [1, 2, 3, 4, 12],
    },
    {
        'artist': 3,
        'title': 'Smile',
        'cover': 'https://i.scdn.co/image/ab67616d0000b2735ebe6cbd74a47a5e8ea88985',
        'description': 'Smile is the sixth studio album by American singer Katy Perry. It was released on August 28, 2020, by Capitol Records, three years after its predecessor Witness.',
        'likes': 2984940,
        'release_date': '2020-08-28',
        'genre': [1],
    },
    {
        'artist': 4,
        'title': 'Divide',
        'cover': 'https://upload.wikimedia.org/wikipedia/en/8/80/Ed_Sheeran_Perfect_Single_cover.jpg',
        'description': '÷ is the third studio album by English singer-songwriter Ed Sheeran. It was released on 3 March 2017 through Asylum Records and Atlantic Records. "Castle on the Hill" and "Shape of You" were released as the albums lead singles on 6 January 2017.',
        'likes': 63789391,
        'release_date': '2017-03-03',
        'genre': [1, 4],
    },
    {
        'artist': 5,
        'title': 'Collage',
        'cover': 'https://upload.wikimedia.org/wikipedia/en/2/22/Collage%2C_album_cover.jpg',
        'description': 'Collage is the second extended play (EP) by American DJ duo The Chainsmokers. It was released on November 4, 2016, through Disruptor Records and Columbia Records.',
        'likes': 6483265829,
        'release_date': '2016-10-04',
        'genre': [10, 13],
    },
    # {
    #     'artist': '',
    #     'title': '',
    #     'cover': '',
    #     'description': '',
    #     'likes': '',
    #     'release_date': '',
    #     'genre': '',
    # },
    # {
    #     'artist': '',
    #     'title': '',
    #     'cover': '',
    #     'description': '',
    #     'likes': '',
    #     'release_date': '',
    #     'genre': '',
    # },
    # {
    #     'artist': '',
    #     'title': '',
    #     'cover': '',
    #     'description': '',
    #     'likes': '',
    #     'release_date': '',
    #     'genre': '',
    # },
    # {
    #     'artist': '',
    #     'title': '',
    #     'cover': '',
    #     'description': '',
    #     'likes': '',
    #     'release_date': '',
    #     'genre': '',
    # },
    # {
    #     'artist': '',
    #     'title': '',
    #     'cover': '',
    #     'description': '',
    #     'likes': '',
    #     'release_date': '',
    #     'genre': '',
    # },
    # {
    #     'artist': '',
    #     'title': '',
    #     'cover': '',
    #     'description': '',
    #     'likes': '',
    #     'release_date': '',
    #     'genre': '',
    # },
    # {
    #     'artist': '',
    #     'title': '',
    #     'cover': '',
    #     'description': '',
    #     'likes': '',
    #     'release_date': '',
    #     'genre': '',
    # },

]