# Generated by Django 4.1.3 on 2022-11-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=200)),
                ('likes', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('listeners', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hip hop', 'Hip hop'), ('electronic music', 'Electronic Music'), ('jazz', 'Jazz'), ('country music', 'Country Music'), ('classical music', 'Classical Music'), ('rap', 'Rap'), ('house music', 'House Music'), ('dubstep', 'Dubstep'), ('disco', 'Disco'), ('instrument', 'Instrument'), ('electronic dance music', 'Electronic Dance Music'), ('indie rock', 'Indie Rock')], max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cover', models.ImageField(upload_to='')),
                ('time', models.TimeField()),
                ('plays', models.CharField(blank=True, max_length=50, null=True)),
                ('likes', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replayso.album')),
                ('artist', models.ManyToManyField(to='replayso.artist')),
                ('genre', models.ManyToManyField(to='replayso.genre')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(to='replayso.genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replayso.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(to='replayso.genre'),
        ),
    ]
